<a href="https://colab.research.google.com/github/europecodingschool/ECS---VB---YZ---08.26/blob/main/VB_YZ_Ders_19_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv("/content/kredi_basvurulari.csv")

**1- MODELİ EĞİTMEK**

In [7]:
df.head()

,yas,calisma_tipi,calisma_suresi_yil,ev_durumu,aylik_gelir,kredi_skoru,kredi_tutari,vade_ay,onay
0,25,Serbest,2,Kira,39500,1621,225000,36,1
1,55,Özel Sektör,24,Kira,102000,1616,800000,24,1
2,50,Serbest,12,Ev Sahibi,73500,1066,230000,24,0
3,40,Kamu,6,Kira,48000,1552,175000,12,1
4,40,Özel Sektör,9,Kira,64000,1691,75000,36,1

In [9]:
df.shape

(4000, 9)

In [11]:
#Hızlı Kontroller
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   yas                 4000 non-null   int64
 1   calisma_tipi        4000 non-null   object
 2   calisma_suresi_yil  4000 non-null   int64
 3   ev_durumu           4000 non-null   object
 4   aylik_gelir         4000 non-null   int64
 5   kredi_skoru         4000 non-null   int64
 6   kredi_tutari        4000 non-null   int64
 7   vade_ay             4000 non-null   int64
 8   onay                4000 non-null   int64
dtypes: int64(7), object(2)
memory usage: 281.4+ KB

In [13]:
df.isnull().sum()

yas                   0
calisma_tipi          0
calisma_suresi_yil    0
ev_durumu             0
aylik_gelir           0
kredi_skoru           0
kredi_tutari          0
vade_ay               0
onay                  0
dtype: int64

In [15]:
df["onay"].value_counts()

onay
1    3114
0     886
Name: count, dtype: int64

In [17]:
df["calisma_tipi"].value_counts()

calisma_tipi
Özel Sektör    2251
Kamu            989
Serbest         760
Name: count, dtype: int64

In [19]:
df["ev_durumu"].value_counts()

ev_durumu
Kira         1968
Ev Sahibi    1251
Aile Yanı     781
Name: count, dtype: int64

In [23]:
#X-y train test Ayrımı

from sklearn.model_selection import train_test_split

X = df.drop("onay", axis=1)
y = df["onay"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Eğitim:", X_train.shape, y_train.shape)
print("Test:", X_test.shape, y_test.shape)

Eğitim: (3200, 8) (3200,)
Test: (800, 8) (800,)