<a href="https://colab.research.google.com/github/europecodingschool/ECS---VB---YZ---08.26/blob/main/VB_YZ_Ders_10_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [7]:
df = pd.read_csv("/content/Audi_A1_listings.csv")
#https://www.kaggle.com/datasets/jacklacey/audi-a1-listings/data - datamızı aldığımız yer.

SÜTUN AÇIKLAMALARI
**kalın metin**
Year (Yıl / Model Yılı): Aracın trafiğe tescil edildiği veya üretildiği yıl.

Type (Kasa Tipi / Tür): Aracın gövde tipi (örneğin; Sedan, Hatchback, SUV vb.).

Mileage(miles) (Kilometre / Mil): Aracın o güne kadar yaptığı toplam yol mesafesi (mil cinsinden).

Engine (Motor Hacmi): Motorun silindir hacmi (litre cinsinden, örn. 1.6L, 2.0L).

PS (Beygir Gücü - Metrik): Pferdestärke teriminin kısaltmasıdır; aracın motor gücünü ifade eder (1 PS, yaklaşık 0,986 İngiliz beygir gücüne - HP'ye eşittir).

Transmission (Şanzıman / Vites Tipi): Aracın vites türü (manuel, otomatik veya yarı otomatik).

Fuel (Yakıt Tipi): Aracın kullandığı yakıt türü (benzin, dizel, hibrit, elektrik vb.).

Number_of_Owners (Önceki Sahip Sayısı): Aracın daha önce kaç farklı kişi veya kurum tarafından sahiplenildiğini gösteren sayı.

Price(£) (Fiyat): Aracın İngiliz sterlini (£) cinsinden satış fiyatı.

href (İlan Bağlantısı): İlgili araç ilanının internet adresi veya web bağlantı linki.

PPY - Price Per Year (Yıllık Maliyet): Aracın Fiyatı / (10 - Aracın Yaşı) formülüyle hesaplanan metrik. Aracı 10 yaşına geldiğinde satmayı planladığınız varsayımıyla, kalan yıllar boyunca aracın size yıllık maliyetini gösterir.

MileageRank (Kilometre Sıralaması): Aracın veri kümesindeki mil sıralaması. Kilometresi daha düşük olan araçlara daha yüksek/iyi bir derece verilir.

PriceRank (Fiyat Sıralaması): Aracın veri kümesindeki fiyat sıralaması. Fiyatı daha ucuz olan araçlara daha yüksek/iyi bir derece verilir.

PPYRank (Yıllık Maliyet Sıralaması): Aracın yıllık maliyetine (PPY) göre veri kümesindeki sırası. Yıllık maliyeti daha düşük olan araçlar daha üst/iyi sırada yer alır.

Score (Toplam Skor / Puan): MileageRank, PriceRank ve PPYRank değerlerinin toplamı. Hem ucuz hem az kullanılmış hem de yıllık maliyeti düşük olan en avantajlı araçları tespit etmek için kullanılan genel bir değerlendirme puanıdır.

In [9]:
df.head() #en tepe 5 indexi getirdi.

,index,Year,Type,Mileage(miles),Engine,PS,Transmission,Fuel,Number_of_Owners,Price(£),href,PPY,MileageRank,PriceRank,PPYRank,Score
0,0,2018.0,Hatchback,44000.0,1.6L,114.398422,Manual,Diesel,1,14995.0,https://www.autotrader.co.uk/car-details/20221...,2499.166667,215,163,340,718
1,4,2016.0,Hatchback,42596.0,1.0L,93.688363,Manual,Petrol,3,10755.0,https://www.autotrader.co.uk/car-details/20221...,2688.750000,222,330,276,828
2,7,2015.0,Hatchback,42700.0,1.4L,123.274162,Manual,Petrol,2,10799.0,https://www.autotrader.co.uk/car-details/20221...,3599.666667,221,327,94,642
3,11,2014.0,Hatchback,86000.0,1.6L,103.550296,Manual,Diesel,3,7490.0,https://www.autotrader.co.uk/car-details/20221...,3745.000000,41,449,83,573
4,12,2014.0,Hatchback,104310.0,1.6L,103.550296,Manual,Diesel,3,7400.0,https://www.autotrader.co.uk/car-details/20220...,3700.000000,12,452,85,549

In [11]:
df.tail() # en alt 5 indexi getirdi.

,index,Year,Type,Mileage(miles),Engine,PS,Transmission,Fuel,Number_of_Owners,Price(£),href,PPY,MileageRank,PriceRank,PPYRank,Score
466,985,2014.0,Hatchback,40195.0,1.4L,138.067061,Automatic,Petrol,3,11275.0,https://www.autotrader.co.uk/car-details/20220...,5637.500000,236,302,12,550
467,986,2020.0,Hatchback,26218.0,1.0L,114.398422,Manual,Petrol,1,18495.0,https://www.autotrader.co.uk/car-details/20221...,2311.875000,342,93,404,839
468,987,2017.0,Hatchback,48571.0,1.4L,123.274162,Manual,Petrol,2,11995.0,https://www.autotrader.co.uk/car-details/20221...,2399.000000,190,257,372,819
469,988,2020.0,Hatchback,9584.0,1.0L,93.688363,Manual,Petrol,1,19970.0,https://www.autotrader.co.uk/car-details/20221...,2496.250000,444,64,346,854
470,990,2019.0,Hatchback,17303.0,1.0L,114.398422,Manual,Petrol,1,17195.0,https://www.autotrader.co.uk/car-details/20221...,2456.428571,399,125,360,884

In [13]:
df.info() #dataframe hakkında genel bilgilendirme. sütunların data tipleri ve sayıları.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 471 entries, 0 to 470
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             471 non-null    int64
 1   Year              471 non-null    float64
 2   Type              471 non-null    object
 3   Mileage(miles)    471 non-null    float64
 4   Engine            471 non-null    object
 5   PS                471 non-null    float64
 6   Transmission      471 non-null    object
 7   Fuel              471 non-null    object
 8   Number_of_Owners  471 non-null    int64
 9   Price(£)          471 non-null    float64
 10  href              471 non-null    object
 11  PPY               471 non-null    float64
 12  MileageRank       471 non-null    int64
 13  PriceRank         471 non-null    int64
 14  PPYRank           471 non-null    int64
 15  Score             471 non-null    int64
dtypes: float64(5), int64(6), object(5)
memory usage: 59.0+ KB

In [16]:
df.isnull().sum() # sütunlarımızda boş değer var mı? toplamı.

index               0
Year                0
Type                0
Mileage(miles)      0
Engine              0
PS                  0
Transmission        0
Fuel                0
Number_of_Owners    0
Price(£)            0
href                0
PPY                 0
MileageRank         0
PriceRank           0
PPYRank             0
Score               0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.nunique()

index               471
Year                  9
Type                  1
Mileage(miles)      416
Engine                6
PS                   28
Transmission          2
Fuel                  2
Number_of_Owners      7
Price(£)            356
href                471
PPY                 406
MileageRank         471
PriceRank           471
PPYRank             471
Score               306
dtype: int64

In [22]:
df.describe()

,index,Year,Mileage(miles),PS,Number_of_Owners,Price(£),PPY,MileageRank,PriceRank,PPYRank,Score
count,471.000000,471.000000,471.000000,471.000000,471.000000,471.000000,471.000000,471.000000,471.000000,471.000000,471.000000
mean,514.104034,2016.970276,44892.783439,116.682559,1.785563,13935.070064,3048.577682,235.000000,235.000000,235.000000,705.000000
std,280.877333,2.208101,27020.236124,17.345034,0.886473,4955.040914,896.647265,136.110249,136.110249,136.110249,139.228925
min,0.000000,2014.000000,9.000000,84.812623,1.000000,5000.000000,1682.333333,0.000000,0.000000,0.000000,299.000000
25%,280.000000,2015.000000,24902.000000,103.550296,1.000000,10286.500000,2481.666667,117.500000,117.500000,117.500000,595.000000
50%,519.000000,2017.000000,40236.000000,114.398422,2.000000,12495.000000,2800.000000,235.000000,235.000000,235.000000,704.000000
75%,754.500000,2019.000000,61770.500000,123.274162,2.000000,17495.000000,3342.400000,352.500000,352.500000,352.500000,809.000000
max,990.000000,2022.000000,149000.000000,197.238659,7.000000,30450.000000,7375.000000,470.000000,470.000000,470.000000,1034.000000

In [24]:
df.columns

Index(['index', 'Year', 'Type', 'Mileage(miles)', 'Engine', 'PS',
       'Transmission', 'Fuel', 'Number_of_Owners', 'Price(£)', 'href', 'PPY',
       'MileageRank', 'PriceRank', 'PPYRank', 'Score'],
      dtype='object')

In [ ]:
#makine öğrenmesi modelinde işimize yaramayacak sütunlar: (index,href, Type, 'PPY', 'MileageRank', 'PriceRank', 'PPYRank', 'Score')